#!/bin/bash
# Emit CMake + Meson cross files inside a built toolchain prefix.
#
# Usage: emit-toolchain-files.sh <TARGET> <PREFIX> <CT_NG_CONFIG>
#
# Writes:
#   <PREFIX>/share/cmake/<TARGET>.toolchain.cmake
#   <PREFIX>/share/meson/<TARGET>-cross.ini
#
# Paths baked into the files are <PREFIX>/... so the toolchain is
# still usable from its expected install location (typically
# /opt/x-tools/<TARGET>).

set -euo pipefail

if [[ $# -lt 3 ]]; then
    echo "Usage: $0 <TARGET> <PREFIX> <CT_NG_CONFIG>" >&2
    exit 1
fi

TARGET=$1
PREFIX=$2
CONFIG=$3

ARCH_CPU=$(grep -E '^CT_ARCH_CPU="' "${CONFIG}" | cut -d'"' -f2 || true)

case "${TARGET}" in
    aarch64-*)
        MESON_CPU_FAMILY=aarch64
        CMAKE_PROCESSOR=aarch64
        ;;
    armv*-*)
        MESON_CPU_FAMILY=arm
        CMAKE_PROCESSOR=arm
        ;;
    *)
        echo "Unknown target family for ${TARGET}" >&2
        exit 1
        ;;
esac

MESON_CPU="${ARCH_CPU:-${CMAKE_PROCESSOR}}"

sudo mkdir -p "${PREFIX}/share/cmake" "${PREFIX}/share/meson"

sudo tee "${PREFIX}/share/cmake/${TARGET}.toolchain.cmake" >/dev/null <<CMAKE
# Auto-generated by rpi-cross (https://github.com/gfunkmonk/rpi-cross).
# Use with: cmake -DCMAKE_TOOLCHAIN_FILE=${PREFIX}/share/cmake/${TARGET}.toolchain.cmake
set(CMAKE_SYSTEM_NAME      Linux)
set(CMAKE_SYSTEM_PROCESSOR ${CMAKE_PROCESSOR})

set(CMAKE_SYSROOT          ${PREFIX}/${TARGET}/sysroot)

set(CMAKE_C_COMPILER       ${PREFIX}/bin/${TARGET}-gcc)
set(CMAKE_CXX_COMPILER     ${PREFIX}/bin/${TARGET}-g++)
set(CMAKE_ASM_COMPILER     ${PREFIX}/bin/${TARGET}-gcc)
set(CMAKE_LINKER           ${PREFIX}/bin/${TARGET}-ld)
set(CMAKE_AR               ${PREFIX}/bin/${TARGET}-ar)
set(CMAKE_RANLIB           ${PREFIX}/bin/${TARGET}-ranlib)
set(CMAKE_STRIP            ${PREFIX}/bin/${TARGET}-strip)
set(CMAKE_OBJCOPY          ${PREFIX}/bin/${TARGET}-objcopy)
set(CMAKE_OBJDUMP          ${PREFIX}/bin/${TARGET}-objdump)

# Search for programs on the host, but libs/headers/packages in the target sysroot.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
CMAKE

sudo tee "${PREFIX}/share/meson/${TARGET}-cross.ini" >/dev/null <<MESON
# Auto-generated by rpi-cross (https://github.com/gfunkmonk/rpi-cross).
# Use with: meson setup build --cross-file=${PREFIX}/share/meson/${TARGET}-cross.ini
[binaries]
c         = '${PREFIX}/bin/${TARGET}-gcc'
cpp       = '${PREFIX}/bin/${TARGET}-g++'
ar        = '${PREFIX}/bin/${TARGET}-ar'
strip     = '${PREFIX}/bin/${TARGET}-strip'
objcopy   = '${PREFIX}/bin/${TARGET}-objcopy'
pkg-config = 'pkg-config'

[properties]
sys_root  = '${PREFIX}/${TARGET}/sysroot'

[host_machine]
system     = 'linux'
cpu_family = '${MESON_CPU_FAMILY}'
cpu        = '${MESON_CPU}'
endian     = 'little'
MESON

echo "Wrote ${PREFIX}/share/cmake/${TARGET}.toolchain.cmake"
echo "Wrote ${PREFIX}/share/meson/${TARGET}-cross.ini"
