#!/bin/bash
# Emit CMake + Meson cross files inside a built toolchain prefix.
#
# Usage: emit-toolchain-files.sh <TARGET> <PREFIX> <CT_NG_CONFIG>
#
# Writes:
#   <PREFIX>/share/cmake/<TARGET>.toolchain.cmake
#   <PREFIX>/share/meson/<TARGET>-cross.ini
#
# Paths baked into the files are <PREFIX>/... so the toolchain is
# still usable from its expected install location (typically
# /opt/x-tools/<TARGET>).

set -euo pipefail

if [[ $# -lt 3 ]]; then
    echo "Usage: $0 <TARGET> <PREFIX> <CT_NG_CONFIG>" >&2
    exit 1
fi

TARGET=$1
PREFIX=$2
CONFIG=$3

ARCH_CPU=$(grep -E '^CT_ARCH_CPU="' "${CONFIG}" | cut -d'"' -f2 || true)

case "${TARGET}" in
    aarch64-*)
        MESON_CPU_FAMILY=aarch64
        CMAKE_PROCESSOR=aarch64
        ;;
    arm-*|armv[4-8]*-*)
        MESON_CPU_FAMILY=arm
        CMAKE_PROCESSOR=arm
        ;;
    *)
        echo "Unknown target family for ${TARGET}" >&2
        exit 1
        ;;
esac

MESON_CPU="${ARCH_CPU:-${CMAKE_PROCESSOR}}"

# Linux targets have <PREFIX>/<TARGET>/sysroot; bare-metal (pico, *-eabi / *-eabihf)
# do not and require CMAKE_SYSTEM_NAME=Generic / Meson system='none'. Unknown
# OS/ABI triples are a hard error rather than silently emitting Pico-style files.
case "${TARGET}" in
    *-linux-*|*-musl*|*-uclibc*|*-gnu*)
        CMAKE_SYSTEM_NAME=Linux
        MESON_SYSTEM=linux
        BARE_METAL=0
        ;;
    *-eabi|*-eabihf)
        CMAKE_SYSTEM_NAME=Generic
        MESON_SYSTEM=none
        BARE_METAL=1
        ;;
    *)
        echo "Unknown target OS/ABI for ${TARGET}" >&2
        exit 1
        ;;
esac

sudo mkdir -p "${PREFIX}/share/cmake" "${PREFIX}/share/meson"

if [[ "${BARE_METAL}" -eq 0 ]]; then
    CMAKE_SYSROOT_LINE="set(CMAKE_SYSROOT          ${PREFIX}/${TARGET}/sysroot)"
    MESON_SYSROOT_BLOCK="[properties]
sys_root  = '${PREFIX}/${TARGET}/sysroot'
"
else
    # No Linux-style sysroot for bare-metal; cmake's try_compile must skip link,
    # and we still need to scope find_{library,path,package} (which we set to
    # ONLY below) to the toolchain prefix so downstream projects can resolve
    # headers and libraries shipped inside the toolchain.
    CMAKE_SYSROOT_LINE="set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH        ${PREFIX}/${TARGET})"
    MESON_SYSROOT_BLOCK=""
fi

sudo tee "${PREFIX}/share/cmake/${TARGET}.toolchain.cmake" >/dev/null <<CMAKE
# Auto-generated by rpi-cross (https://github.com/gfunkmonk/rpi-cross).
# Use with: cmake -DCMAKE_TOOLCHAIN_FILE=${PREFIX}/share/cmake/${TARGET}.toolchain.cmake
set(CMAKE_SYSTEM_NAME      ${CMAKE_SYSTEM_NAME})
set(CMAKE_SYSTEM_PROCESSOR ${CMAKE_PROCESSOR})

${CMAKE_SYSROOT_LINE}

set(CMAKE_C_COMPILER       ${PREFIX}/bin/${TARGET}-gcc)
set(CMAKE_CXX_COMPILER     ${PREFIX}/bin/${TARGET}-g++)
set(CMAKE_ASM_COMPILER     ${PREFIX}/bin/${TARGET}-gcc)
set(CMAKE_LINKER           ${PREFIX}/bin/${TARGET}-ld)
set(CMAKE_AR               ${PREFIX}/bin/${TARGET}-ar)
set(CMAKE_RANLIB           ${PREFIX}/bin/${TARGET}-ranlib)
set(CMAKE_STRIP            ${PREFIX}/bin/${TARGET}-strip)
set(CMAKE_OBJCOPY          ${PREFIX}/bin/${TARGET}-objcopy)
set(CMAKE_OBJDUMP          ${PREFIX}/bin/${TARGET}-objdump)

# Search for programs on the host, but libs/headers/packages in the target sysroot.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
CMAKE

sudo tee "${PREFIX}/share/meson/${TARGET}-cross.ini" >/dev/null <<MESON
# Auto-generated by rpi-cross (https://github.com/gfunkmonk/rpi-cross).
# Use with: meson setup build --cross-file=${PREFIX}/share/meson/${TARGET}-cross.ini
[binaries]
c         = '${PREFIX}/bin/${TARGET}-gcc'
cpp       = '${PREFIX}/bin/${TARGET}-g++'
ar        = '${PREFIX}/bin/${TARGET}-ar'
strip     = '${PREFIX}/bin/${TARGET}-strip'
objcopy   = '${PREFIX}/bin/${TARGET}-objcopy'
pkg-config = 'pkg-config'

${MESON_SYSROOT_BLOCK}[host_machine]
system     = '${MESON_SYSTEM}'
cpu_family = '${MESON_CPU_FAMILY}'
cpu        = '${MESON_CPU}'
endian     = 'little'
MESON

echo "Wrote ${PREFIX}/share/cmake/${TARGET}.toolchain.cmake"
echo "Wrote ${PREFIX}/share/meson/${TARGET}-cross.ini"
